### ISSUE TITLE
router urls with "?"

### ISSUE THREAD

**Issue by scottiedog45** [glock45/swifter#378]
First and foremost thanks for the fun library! Makes my integration tests pretty painless =)

Perhaps I've missed something in the docs, but:

Going from version 1.4.5 -> 1.4.6, it seems Swifter is unable to correctly parse the following url when my app requests it:

`/invoices/?page=1`

The package IS able to find the file with the json in it, but when my app makes a request to this url in `1.4.6`, I get a 404. 

The 1.4.5 version correctly finds it!

What do you advise?

All other types of routes without the `?` work fine. 

Thanks =)

**Comment by Vkt0r** [comment]
Hey, @scottiedog45 👋 Thanks for reporting this and for your kind words! Unfortunately, we're not supporting query parameters yet in the library, by default there are stripped when the route is registered or the route is received. 

So this means that `/invoices/?page=1` it should be equal to `/invoices/?page=2` and equal to `/invoices` by default. There is an open discussion in #346 and that's something we're planning to support.

**Comment by DrBeak1** [comment]
@scottiedog45 if you're just trying to differentiate between requests based on params you can use the same route, just check the `queryParams` variable on the request object.

However, I actually do **not** believe that's what you're asking. If I understand correctly you're saying that you have the `/invoces` route set up and when you call `/invoces/?page=1` you're seeing a 404 response. Is that correct? I found your thread here because I was seeing 404 errors for routes I've defined on the server. Swifter even reports that the route is in fact there.

I'm calling:
`print("ROUTES: \(server.routes as NSArray)")`
Which prints out the expected route. I've triple checked that the route is correctly defined and called; but still seeing 404s. I'm not sure what the issue is. The path is actually pretty standard:
`/user/v1/orders/score/pending`

If I misunderstood let me know and I'll create a separate ticket, but I think we may be seeing the same issue. I should note that this was a problem for me in 1.4.5, too - so not new to 1.4.6.

**Comment by Vkt0r** [comment]
@scottiedog45  Can you please point your `Podfile` or `Cartfile` to #382 and give a try with your current repository and let me know if the issue was fixed?
