### ISSUE TITLE
Error status code is not returned

### ISSUE THREAD

**Issue by anyfuncyo** [glock45/swifter#455]
I am trying to build a proxy server for UI tests. In the app code, an unauthorised alert will appear if the error code returned is 401. I have tested with the server endpoint and the app code work as expected.  However I get 404 instead of 401 when pointing the app to the proxy server.

Here's how I set the response returned in my proxy server:
```
func setResponse(for endpoint: MockServer.Endpoint) -> HttpResponse {
        switch (endpoint, self) {
        case(.countryData, .success):
            return .ok(.data(MockServer.shared.getDummyData(resource: "countryData", fileFormat: "json")))
        case(.countryData, .failure):
            return .internalServerError
        case(.countryData, .unauthorized):
            return .unauthorized
        }
}
```

Both ` .internalServerError` and `.unauthorized` returned with statusCode of 404, instead of `500` and `401` as suggested. in the Swifter. Any idea how should I set up the proxy server to respond with a customised error code?

**Comment by Vkt0r** [comment]
Hey, @anyfuncyo Thanks for reporting this! A little weird that the status code for `.internalServerError` and `.unauthorized` is wrong because we return correct status code and you can see it here:

https://github.com/httpswift/swifter/blob/e9b1d5ef5a8683babe4265007779a87c324abf8a/XCode/Sources/HttpResponse.swift#L90-L105

Nevertheless, if you want to return your own response code you can always use the `case .raw(let code, _, _, _)` and handle the type of error yourself.

**Comment by Vkt0r** [comment]
Closing this, feel free to open it if you have any more doubts or issues.
