### ISSUE TITLE
Use blue folder containing html files

### ISSUE THREAD

**Issue by SamDecrock** [glock45/swifter#64]
Hi,

This is not an issue, but I just wanted to let you know that I'm adding complete folders to my Bundle (by adding them as folder, not as group) and then using this code to access them:

```Swift

server["/public/(.+)"] = directory("HTML/")

func directory(dir: String) -> ( HttpRequest -> HttpResponse ) {
    return { request in
        if let localPath = request.capturedUrlGroups.first {
            print(localPath)
            if let filesPath = NSBundle.mainBundle().pathForResource(dir + localPath, ofType: "") {
                print(filesPath)
                if let fileBody = NSData(contentsOfFile: filesPath) {
                    return HttpResponse.RAW(200, "OK", nil, fileBody)
                }
            }
        }
        return HttpResponse.NotFound
    }
}
```

Where ```HTML/``` is the blue folder added to my iOS project.

So by going to http://url-to-iphone:port/public/index.html i'm accessing ```index.html``` inside the ```HTML/```-folder

**Comment by glock45** [comment]
hi @SamDecrock 

Thanks for the message. Answering to your question, yes, I know about that. It's because of the bundle structure and how iOS build procedure treats resources files. According to https://developer.apple.com/library/ios/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html all the files are copied to the root of bundle:

>A typical iOS application bundle contains the application executable and any resources used by the application (for instance, the application icon, other images, and localized content) in the top-level bundle directory.



best
dk
